### ISSUE TITLE
左上角的 addButton 自定化需求

### ISSUE THREAD

**Issue by cjfff** [FEMessage/el-data-tree#3]
**Is your feature request related to a problem? Please describe.**
树组件右上方的 `addButton` 无法自定义, 目前 `api` 文档中只给出 `hasAdd: boolean` 是否显示按钮开关，但有时候业务上面需要自定义化

**Describe the solution you'd like**
开放一个插槽，例如:

定义:
```js
<span v-if="hasAdd" @click="onDefaultNew">
  <slot name="headerAdd">
      < i class="el-icon-plus" ></i>
  </slot>
</span>
```

使用:
```js
 <el-data-tree>
     <el-button slot="headerAdd"  type="text" >添加节点</el-button>
 </el-data-tree>
```

**Additional context**
![image](https://user-images.githubusercontent.com/20502762/56642868-fc9afd00-66aa-11e9-9401-7ca507f2fa4d.png)

**Comment by donaldshen** [comment]
其实title部分目前整体是个slot，你可以随意定制。
```vue
<el-data-tree hasTitle><p slot="title">title</p></el-data-tree>
```

**Comment by cjfff** [comment]
已解决问题
