### ISSUE TITLE
beforeConfirm 方法在 confirm 方法内部执行?

### ISSUE THREAD

**Issue by shoyuf** [FEMessage/el-data-tree#30]
https://github.com/FEMessage/el-data-tree/blob/e9631d9395431ebc10f4483240456827c4889a12/src/el-data-tree.vue#L583-L602

为什么 beforeConfirm 方法在 confirm 方法内部执行?
如果需要在触发 confirm 后修改 extraParams 有办法实现吗?

**Comment by lianghx-319** [comment]
在触发 confirm 后修改 extraParams，有具体的使用场景吗？

**Comment by levy9527** [comment]
猜测是前端组件数据与后端数据格式不匹配吧。可以使用@femeesage/el-form-renderer的inputFormat/outputFormat

**Comment by shoyuf** [comment]
> 在触发 confirm 后修改 extraParams，有具体的使用场景吗？

当时是想在顶级新增和子集新增共用一个默认的MessageBox confirm，因为两种新增所传参数不一样，所以想在confirm 里点击确认之前修改
