### ISSUE TITLE
懒加载后，如果没有子节点，父节点收不回去

### ISSUE THREAD

**Issue by linrunzheng** [FEMessage/el-data-tree#33]
**Describe the bug**

采用异步加载子节点的方式，当点击某一级别时，如果下面没有子节点，则父节点收起点击失效

**Comment by qiaoqiao10001** [comment]
还没有人解决吗

**Comment by levy9527** [comment]
> 还没有人解决吗

下周发版本哈

**Comment by lianghx-319** [comment]
@linrunzheng 有当时的图和代码吗...现在只能凭印象debug了

**Comment by qiaoqiao10001** [comment]
![image](https://user-images.githubusercontent.com/25581172/60250051-827c3400-98f8-11e9-80d2-805c667d71ce.png)
![image](https://user-images.githubusercontent.com/25581172/60250063-8740e800-98f8-11e9-9664-d0622c21c3f6.png)
@lianghx-319

**Comment by linrunzheng** [comment]
```javascript
<data-tree
        v-if="!reload"
        ref="tree"
        :props="treeProps"
        v-loading="treeLoading"
        node-key="id"
        lazy
        :load="loadNode"
>

methods:{
    async loadNode(node, resolve) {
      let id = node.data ? node.data.id : null
      !id && (this.treeLoading = true)
      try {
        let data = await this.fetchAppDepartmentTree({
          id,
          appId: this.$store.state.app.appData.id,
          showNamePath: true,
          showManagerAndType: true
        })
        return resolve(data)
      } catch (e) {
        console.log(e)
      } finally {
        this.treeLoading = false
      }
    },
}
```

**Comment by lianghx-319** [comment]
# 子节点展开时，父节点无法收起

<a name="CqJum"></a>
## 解决方案
- 不修改源码，调用组件时，设置 auto-expand-parent 为 false![image.png](https://cdn.nlark.com/yuque/0/2019/png/265497/1561704558454-abb6dc44-ddcd-4283-821b-fbcaf7c6582d.png#align=left&display=inline&height=411&name=image.png&originHeight=411&originWidth=386&size=49247&status=done&width=386) 
- 修改组件源码，不使用更变 defaultExpandKeys 的方式来改变节点的 expanded 状态
  - 这个改动如果不影响外部功能的话，能减少展开折叠的调用栈，因为变更 defaultExpandKeys 需要 watcher 才能响应更新状态。
  - 原理：
    - 更变 defaultExpandKeys 时的调用![image.png](https://cdn.nlark.com/yuque/0/2019/png/265497/1561704845843-701b819d-9822-4eca-a7ed-f15dd2e854ce.png#align=left&display=inline&height=232&name=image.png&originHeight=232&originWidth=576&size=39990&status=done&width=576)
    - 不更变 defaultExpandKeys 时的调用![image.png](https://cdn.nlark.com/yuque/0/2019/png/265497/1561704903205-3d6b2fab-b5d0-490f-8d32-6d8af6e6a24b.png#align=left&display=inline&height=253&name=image.png&originHeight=253&originWidth=586&size=41838&status=done&width=586)
    - 可以看出，不触发 defaultExpandKeys 改变时，会无视 auto-expand-parent 这个属性

<a name="U3UR8"></a>
## Debug 记录

- [issue 链接](https://github.com/FEMessage/el-data-tree/issues/33)
- Debug 方向
  - 折叠列表依靠点击按钮触发
  - 查看相关函数调用栈


<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/265497/1561703782273-9daa9563-a597-4dce-9603-b39ad0405091.png#align=left&display=inline&height=220&name=image.png&originHeight=220&originWidth=865&size=33639&status=done&width=865)

- 打开七宝店 line 1-2
- 打开addbumen line 3-6
- 关闭七宝店 line 7-11

- 因为 addbumen 这个节点异步加载，但是没有子节点，所以看起来时收起的，实际上这个节点的状态是展开的。所以点击关闭七宝店的时候，子节点 addbumen 仍然处于 expanded，而 element 默认 字节展开时，同时展开父节点，所以造成了不能关闭的假象。![image.png](https://cdn.nlark.com/yuque/0/2019/png/265497/1561703961127-c76a6dd1-72f7-45c4-814b-9f47d295fb51.png#align=left&display=inline&height=58&name=image.png&originHeight=58&originWidth=885&size=5959&status=done&width=885)
